package com.pbakhil.iot.app;

import com.microsoft.azure.sdk.iot.service.exceptions.IotHubException;
import com.microsoft.azure.sdk.iot.service.Device;
import com.microsoft.azure.sdk.iot.service.RegistryManager;

import java.io.IOException;
import java.net.URISyntaxException;

public class IOTRegistration {

	private static final String connectionString = "HostName=pbakhiliothub1.azure-devices.net;SharedAccessKeyName=iothubowner;SharedAccessKey=nfzLTSR7eKr7vcEcgQ9Q01f89YhN6f6ism4lEqKYj80=";
	private static final String deviceId = "FirstJavaDevice";

	public static void main(String[] args) {

		try {
			deviceRegistration();
		} catch (IOException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (URISyntaxException e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		} catch (Exception e) {
			// TODO Auto-generated catch block
			e.printStackTrace();
		}
	}

	private static void deviceRegistration() throws IOException, URISyntaxException, Exception {
		RegistryManager registryManager = RegistryManager.createFromConnectionString(connectionString);

		// Create a device that's enabled by default,
		// with an autogenerated key.
		Device device = Device.createFromId(deviceId, null, null);
		try {
			device = registryManager.addDevice(device);
		} catch (IotHubException iote) {
			// If the device already exists.
			try {
				device = registryManager.getDevice(deviceId);
			} catch (IotHubException iotf) {
				iotf.printStackTrace();
			}
		}

		// Display information about the
		// device you created.
		System.out.println("Device Id: " + device.getDeviceId());
		System.out.println("Device key: " + device.getPrimaryKey());
	}

}
